### ISSUE TITLE
linux下可以运行吗

### ISSUE THREAD

**Issue by retaw106** [listen1/listen1#16]
请问这个程序可以在linux下使用吗？
我尝试了下pip install -r requirements/dev.txt， python app.py
然后报错的最后一行是`AttributeError: 'dict_keys' object has no attribute 'index'`
谢谢！

**Comment by listen1** [comment]
请检查一下Python版本，现在的版本没有用Python3做测试，可以尝试用2.x版本的Python运行。

**Comment by retaw106** [comment]
谢谢回答。
我用python2运行时，回车后什么也没有。网页打开localhost:8888显示
`Traceback (most recent call last):
  File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 2149, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found`
此时终端报错：
`[W 160513 20:16:05 web:1946] 404 GET /gui/ (127.0.0.1) 31.52ms
[E 160513 20:16:05 web:1524] Uncaught exception GET /favicon.ico (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 2263, in get
        absolute_path = self.get_absolute_path(self.root, self.path)
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 2406, in get_absolute_path
        abspath = os.path.abspath(os.path.join(root, path))
      File "/usr/lib/python2.7/posixpath.py", line 73, in join
        path += '/' + b
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 12: ordinal not in range(128)
[E 160513 20:16:06 web:1946] 500 GET /favicon.ico (127.0.0.1) 40.82ms
`
这个问题容易解决么？

**Comment by retaw106** [comment]
谢谢回答。
我用python2运行时，回车后什么也没有。网页打开localhost:8888显示
```
Traceback (most recent call last):
  File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 2149, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found
```
此时终端报错：
```
[W 160513 20:16:05 web:1946] 404 GET /gui/ (127.0.0.1) 31.52ms
[E 160513 20:16:05 web:1524] Uncaught exception GET /favicon.ico (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 2263, in get
        absolute_path = self.get_absolute_path(self.root, self.path)
      File "/home/retaw/.local/lib/python2.7/site-packages/tornado/web.py", line 2406, in get_absolute_path
        abspath = os.path.abspath(os.path.join(root, path))
      File "/usr/lib/python2.7/posixpath.py", line 73, in join
        path += '/' + b
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 12: ordinal not in range(128)
[E 160513 20:16:06 web:1946] 500 GET /favicon.ico (127.0.0.1) 40.82ms

```
这个问题容易解决么？

**Comment by listen1** [comment]
看日志貌似没有访问根路径，请确定是访问的 http://localhost:8888/

**Comment by retaw106** [comment]
我是访问的8888没错。如果不是在终端也不会报错啊。看来不是普遍性的问题。
刚刚又试了一下，发现firefox仍然是这个错误；换成chorme后，尽管终端有好长好长的错误反馈，但网页端是有界面的，不过界面没有图片，显示也很混乱。我怀疑可能问题是在浏览器之类的环境上。
发现chorme插件版更新有我的歌单了，试了下能用，先用插件版好了。谢谢了！

**Comment by listen1** [comment]
不客气，enjoy！

**Comment by ruizhipeng** [comment]
前端环境可以考虑用electron

**Comment by retaw106** [comment]
其实我不怎么会应用编程，不过你应该是对作者说的吧。。。。如果是回复我的话，过段时间闲下来了再研究看看吧，谢谢

**Comment by listen1** [comment]
electron 版本正在调研中，敬请期待
